app:
  scheduler:
    enable: true
    interval: 1000
    force-check-delay: 10000

clients:
  github:
    host: https://api.github.com
  stack:
    host: https://api.stackexchange.com/2.3
  bot:
    host: http://localhost:8090

spring:
  application:
    name: scrapper

springdoc:
  swagger-ui:
    path: /swagger-ui

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
