app:
  useQueue: true
  scheduler:
    enable: true
    interval: 20000
    force-check-delay: 10000
  link-updater:
    batch-size: 10
  link-cleaner:
    enable: true
    time-cron-expression: 0 0 2 * * ? # second minute hour dayOfMonth month dayOfWeek
  database-access-type: jpa

management:
  endpoints:
    web:
      exposure:
        include: "info,health,prometheus"
      base-path: /
      path-mapping:
        prometheus: "metrics"
  metrics:
    tags:
      application: "${spring.application.name}"
  server:
    port: 8085

kafka:
  bootstrapAddress: localhost:9092
  groupId: UTBGroupId
  topic: message-update

clients:
  github:
    host: https://api.github.com
  stack:
    host: https://api.stackexchange.com/2.3
  bot:
    host: http://localhost:8090
  strategy: constant
  configurations:
    retry:
      strategy: constant
      max-attempts: 3
      interval: 2
      statuses: 500, 501


spring:
  application:
    name: scrapper
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  cache:
    cache-names:
      - rate-limit-buckets
    caffeine:
      spec: maximumSize=100000,expireAfterAccess=3600s

springdoc:
  swagger-ui:
    path: /swagger-ui

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml


