app:
  scheduler:
    enable: true
    interval: 10000
    force-check-delay: 10000
  link-updater:
    batch-size: 10
  link-cleaner:
    enable: true
    time-cron-expression: 0 0 2 * * ? # second minute hour dayOfMonth month dayOfWeek
  database-access-type: jpa

clients:
  github:
    host: https://api.github.com
  stack:
    host: https://api.stackexchange.com/2.3
  bot:
    host: http://localhost:8090
  strategy: constant
  configurations:
    retry:
      strategy: constant
      max-attempts: 3
      interval: 2
      statuses: 500, 501


spring:
  application:
    name: scrapper
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  cache:
    cache-names:
      - rate-limit-buckets
    caffeine:
      spec: maximumSize=100000,expireAfterAccess=3600s

bucket4j:
  enabled: true
  filters:
    - cache-name: rate-limit-buckets
      strategy: first
      http-response-body: "{ \"status\": 429, \"error\": \"Too Many Requests\", \"message\": \"You have exhausted your API Request Quota\" }"
      rate-limits:
        - cache-key: "getRemoteAddr()"
          bandwidths:
            - capacity: 100
              time: 1
              unit: seconds

springdoc:
  swagger-ui:
    path: /swagger-ui

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml


