app:
  telegram-token: ${TELEGRAM_TOKEN}

management:
  endpoints:
    web:
      exposure:
        include: "info,health,prometheus"
      base-path: /
      path-mapping:
        prometheus: "metrics"
  metrics:
    tags:
      application: "${spring.application.name}"
  server:
    port: 8095

kafka:
  bootstrapAddress: localhost:9092
  groupId: UTBGroupId
  topic: message-update
  dlq: UTB_dlq

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
  liquibase:
    enabled: false
  cache:
    cache-names:
      - rate-limit-buckets
    caffeine:
      spec: maximumSize=100000,expireAfterAccess=3600s

bucket4j:
  enabled: true
  filters:
    - cache-name: rate-limit-buckets
      strategy: first
      http-response-body: "{ \"status\": 429, \"error\": \"Too Many Requests\", \"message\": \"You have exhausted your API Request Quota\" }"
      rate-limits:
        - cache-key: "getRemoteAddr()"
          bandwidths:
            - capacity: 100
              time: 1
              unit: seconds

springdoc:
  swagger-ui:
    path: /swagger-ui

clients:
  scrapper:
    host: http://localhost:8080
  configurations:
    retry:
      strategy: constant
      max-attempts: 3
      interval: 2
      statuses: 500, 501

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml
