app:
  telegram-token: ${TELEGRAM_TOKEN}

  commands:
    /start: Начать работу с ботом и зарегистрироваться
    /help: Отобразить список доступных команд и их описания
    /track: Начать отслеживание ссылки
    /untrack: Прекратить отслеживание ссылки
    /list: Отобразить список отслеживаемых ссылок

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml
